In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
os.getcwd()

'/Users/dhairyashah/Desktop/Python Capstone'

In [3]:
#Task 1 - There are three different tables, making three dataframe in python and saving them as three .csv files.

employee_data = {
    "ID": ["A001", "A002", "A003", "A004", "A005"],
    "Name": ["John Alter", "Alice Luxumberg", "Tom Sabestine", "Nina Adgra", "Amy Johny"],
    "Gender": ["M", "F", "M", "F", "F"],
    "City": ["Paris", "London", "Berlin", "Newyork", "Madrid"],
    "Age": [25, 27, 29, 31, 30]
}

In [4]:
employee_df = pd.DataFrame(employee_data)

employee_df

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [5]:
base_path = os.getcwd()

employee_file = "Employee.csv"

employee_path = os.path.join(base_path, employee_file)

employee_path

'/Users/dhairyashah/Desktop/Python Capstone/Employee.csv'

In [6]:
employee_df.to_csv(employee_path, index=False)

In [7]:
seniority_data = {
    "ID": ["A001", "A002", "A003", "A004", "A005"],
    "Designation Level": [2, 2, 3, 2, 3]
}

In [8]:
seniority_df = pd.DataFrame(seniority_data)

seniority_df

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [9]:
seniority_file = "Seniority.csv"

seniority_path = os.path.join(base_path, seniority_file)

seniority_path

'/Users/dhairyashah/Desktop/Python Capstone/Seniority.csv'

In [10]:
seniority_df.to_csv(seniority_path, index=False)

In [11]:
project_data = {
    "ID": ["A001", "A002", "A003", "A004", "A005",
           "A002", "A005", "A003", "A001", "A003",
           "A001", "A004", "A004", "A005"],

    "Project": ["Project 1", "Project 2", "Project 3", "Project 4", "Project 5",
                "Project 6", "Project 7", "Project 8", "Project 9", "Project 10",
                "Project 11", "Project 12", "Project 13", "Project 14"],

    "Cost": [1002000, 2000000, 4500000, 5500000, np.nan,
             680000, 400000, 350000, np.nan, 300000,
             2000000, 1000000, 3000000, 200000],

    "Status": ["Finished", "Ongoing", "Finished", "Ongoing", "Finished",
               "Failed", "Finished", "Failed", "Ongoing", "Finished",
               "Failed", "Ongoing", "Finished", "Finished"]
}

In [12]:
project_df = pd.DataFrame(project_data)

project_df

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [13]:
project_file = "Project.csv"

project_path = os.path.join(base_path, project_file)

project_path

'/Users/dhairyashah/Desktop/Python Capstone/Project.csv'

In [14]:
project_df.to_csv(project_path, index=False)

In [15]:
#Task 2 - The cost column in the dataframe “Project” has some missing values. 
        #Computing these missing values and replacing with running avergae using "for" loop.

project_df = pd.read_csv(project_path)

project_df

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [16]:
total_sum = 0
count = 0

for i in range(len(project_df)):
    
    if pd.isna(project_df.loc[i, "Cost"]):
        
        average = total_sum/count
        
        project_df.loc[i, "Cost"] = average
    
    else:
        total_sum += project_df.loc[i, "Cost"]
        
        count += 1

In [17]:
project_df

      ID     Project          Cost    Status
0   A001   Project 1  1.002000e+06  Finished
1   A002   Project 2  2.000000e+06   Ongoing
2   A003   Project 3  4.500000e+06  Finished
3   A004   Project 4  5.500000e+06   Ongoing
4   A005   Project 5  3.250500e+06  Finished
5   A002   Project 6  6.800000e+05    Failed
6   A005   Project 7  4.000000e+05  Finished
7   A003   Project 8  3.500000e+05    Failed
8   A001   Project 9  2.061714e+06   Ongoing
9   A003  Project 10  3.000000e+05  Finished
10  A001  Project 11  2.000000e+06    Failed
11  A004  Project 12  1.000000e+06   Ongoing
12  A004  Project 13  3.000000e+06  Finished
13  A005  Project 14  2.000000e+05  Finished

In [18]:
project_df.to_csv(project_path, index=False)

In [19]:
#Task 3 - Splitting the name column in the Employee dataframe into two new columns “First Name”, and "Last Name" and removing "name" column

employee_df = pd.read_csv(employee_path)

employee_df

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [20]:
employee_df[["First Name", "Last Name"]] = employee_df["Name"].str.split(" ", expand=True)

In [21]:
employee_df.drop("Name", axis=1, inplace=True)

In [22]:
employee_df.to_csv(employee_path, index=False)

In [23]:
employee_df

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

In [24]:
employee_df.to_csv(employee_path, index=False)

In [25]:
#Task 4 - Joining all three dataframes in one single dataframe and naming it "final"

employee_df = pd.read_csv(employee_path)

seniority_df = pd.read_csv(seniority_path)

project_df = pd.read_csv(project_path)

employee_df, seniority_df, project_df

(     ID Gender     City  Age First Name  Last Name
 0  A001      M    Paris   25       John      Alter
 1  A002      F   London   27      Alice  Luxumberg
 2  A003      M   Berlin   29        Tom  Sabestine
 3  A004      F  Newyork   31       Nina      Adgra
 4  A005      F   Madrid   30        Amy      Johny,
      ID  Designation Level
 0  A001                  2
 1  A002                  2
 2  A003                  3
 3  A004                  2
 4  A005                  3,
       ID     Project          Cost    Status
 0   A001   Project 1  1.002000e+06  Finished
 1   A002   Project 2  2.000000e+06   Ongoing
 2   A003   Project 3  4.500000e+06  Finished
 3   A004   Project 4  5.500000e+06   Ongoing
 4   A005   Project 5  3.250500e+06  Finished
 5   A002   Project 6  6.800000e+05    Failed
 6   A005   Project 7  4.000000e+05  Finished
 7   A003   Project 8  3.500000e+05    Failed
 8   A001   Project 9  2.061714e+06   Ongoing
 9   A003  Project 10  3.000000e+05  Finished
 10  A001  Project 11  2.000000e+06    Failed
 11  A004  Project 12  1.000000e+06   Ongoing
 12  A004  Project 13  3.000000e+06  Finished
 13  A005  Project 14  2.000000e+05  Finished)

In [26]:
emp_seniority_df = pd.merge(employee_df, seniority_df, on="ID", how="inner")

emp_seniority_df

     ID Gender     City  Age First Name  Last Name  Designation Level
0  A001      M    Paris   25       John      Alter                  2
1  A002      F   London   27      Alice  Luxumberg                  2
2  A003      M   Berlin   29        Tom  Sabestine                  3
3  A004      F  Newyork   31       Nina      Adgra                  2
4  A005      F   Madrid   30        Amy      Johny                  3

In [27]:
final_df = pd.merge(emp_seniority_df, project_df, on="ID", how="inner")

final_df

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status
0,A001,M,Paris,25,John,Alter,2,Project 1,1.002000e+06,Finished
1,A001,M,Paris,25,John,Alter,2,Project 9,2.061714e+06,Ongoing
2,A001,M,Paris,25,John,Alter,2,Project 11,2.000000e+06,Failed
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,6.800000e+05,Failed
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4.500000e+06,Finished
6,A003,M,Berlin,29,Tom,Sabestine,3,Project 8,3.500000e+05,Failed
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,3.000000e+05,Finished
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5.500000e+06,Ongoing
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1.000000e+06,Ongoing
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3.000000e+06,Finished
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3.250500e+06,Finished
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,4.000000e+05,Finished
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,2.000000e+05,Finished

In [28]:
#Task 5 - Adding a new bonus column in the Final dataframe. Giving a 5% bonus concerning project cost to the employees who finished projects

final_df

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status
0,A001,M,Paris,25,John,Alter,2,Project 1,1.002000e+06,Finished
1,A001,M,Paris,25,John,Alter,2,Project 9,2.061714e+06,Ongoing
2,A001,M,Paris,25,John,Alter,2,Project 11,2.000000e+06,Failed
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,6.800000e+05,Failed
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4.500000e+06,Finished
6,A003,M,Berlin,29,Tom,Sabestine,3,Project 8,3.500000e+05,Failed
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,3.000000e+05,Finished
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5.500000e+06,Ongoing
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1.000000e+06,Ongoing
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3.000000e+06,Finished
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3.250500e+06,Finished
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,4.000000e+05,Finished
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,2.000000e+05,Finished

In [29]:
final_df["Bonus"] = np.where(
    final_df["Status"] == "Finished",
    final_df["Cost"] * 0.05,
    0
)

In [30]:
final_df

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,M,Paris,25,John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,M,Paris,25,John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,M,Paris,25,John,Alter,2,Project 11,2.000000e+06,Failed,0.0
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,6.800000e+05,Failed,0.0
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,M,Berlin,29,Tom,Sabestine,3,Project 8,3.500000e+05,Failed,0.0
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5.500000e+06,Ongoing,0.0
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1.000000e+06,Ongoing,0.0
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3.000000e+06,Finished,150000.0
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3.250500e+06,Finished,162525.0
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,4.000000e+05,Finished,20000.0
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,2.000000e+05,Finished,10000.0

In [31]:
final_df.to_csv(os.path.join(base_path,"Final.csv"), index=False)

In [32]:
#Task 6 - Demoting the designation of those with project status "fail" by 1 and deleting records of those with designation level above 4.

final_df = pd.read_csv("Final.csv")

final_df

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,M,Paris,25,John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,M,Paris,25,John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,M,Paris,25,John,Alter,2,Project 11,2.000000e+06,Failed,0.0
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,6.800000e+05,Failed,0.0
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,M,Berlin,29,Tom,Sabestine,3,Project 8,3.500000e+05,Failed,0.0
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5.500000e+06,Ongoing,0.0
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1.000000e+06,Ongoing,0.0
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3.000000e+06,Finished,150000.0
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3.250500e+06,Finished,162525.0
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,4.000000e+05,Finished,20000.0
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,2.000000e+05,Finished,10000.0

In [33]:
for i in range(len(final_df)):
    if final_df.loc[i, "Status"] == "Failed":
        final_df.loc[i, "Designation Level"] = final_df.loc[i, "Designation Level"] + 1
    else:
        pass

In [34]:
valid_rows = []

for i in range(len(final_df)):
    if final_df.loc[i, "Designation Level"] <= 4:
        valid_rows.append(i)
    else:
        pass

In [35]:
final_df = final_df.loc[valid_rows]

final_df.reset_index(drop=True, inplace=True)

In [36]:
#Task 7 - Adding “Mr.” and “Mrs.” to the first name column and dropping the gender column.

for i in range(len(final_df)):
    if final_df.loc[i, "Gender"] == "M":
        final_df.loc[i, "First Name"] = "Mr. " + final_df.loc[i, "First Name"]
    elif final_df.loc[i, "Gender"] == "F":
        final_df.loc[i, "First Name"] = "Mrs. " + final_df.loc[i, "First Name"]

In [37]:
final_df.drop("Gender", axis=1, inplace=True)

In [38]:
final_df

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,Paris,25,Mr. John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,Paris,25,Mr. John,Alter,3,Project 11,2.000000e+06,Failed,0.0
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project 6,6.800000e+05,Failed,0.0
5,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,Berlin,29,Mr. Tom,Sabestine,4,Project 8,3.500000e+05,Failed,0.0
7,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 4,5.500000e+06,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 12,1.000000e+06,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 13,3.000000e+06,Finished,150000.0
11,A005,Madrid,30,Mrs. Amy,Johny,3,Project 5,3.250500e+06,Finished,162525.0
12,A005,Madrid,30,Mrs. Amy,Johny,3,Project 7,4.000000e+05,Finished,20000.0
13,A005,Madrid,30,Mrs. Amy,Johny,3,Project 14,2.000000e+05,Finished,10000.0

In [39]:
final_df.to_csv("Final.csv", index=False)

In [40]:
#Task 8 - Promoting designation level by 1 for the employees whose age is more than 29 years using IF condition.

final_df.columns

Index(['ID', 'City', 'Age', 'First Name', 'Last Name', 'Designation Level',
       'Project', 'Cost', 'Status', 'Bonus'],
      dtype='object')

In [41]:
for i in range(len(final_df)):
    
    if final_df.loc[i, "Age"] > 29:
        final_df.loc[i, "Designation Level"] = final_df.loc[i, "Designation Level"] - 1
    else:
        pass

In [42]:
final_df

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,Paris,25,Mr. John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,Paris,25,Mr. John,Alter,3,Project 11,2.000000e+06,Failed,0.0
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project 6,6.800000e+05,Failed,0.0
5,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,Berlin,29,Mr. Tom,Sabestine,4,Project 8,3.500000e+05,Failed,0.0
7,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 4,5.500000e+06,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 12,1.000000e+06,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 13,3.000000e+06,Finished,150000.0
11,A005,Madrid,30,Mrs. Amy,Johny,2,Project 5,3.250500e+06,Finished,162525.0
12,A005,Madrid,30,Mrs. Amy,Johny,2,Project 7,4.000000e+05,Finished,20000.0
13,A005,Madrid,30,Mrs. Amy,Johny,2,Project 14,2.000000e+05,Finished,10000.0

In [43]:
final_df.to_csv("Final.csv", index=False)

In [44]:
#Task 9 - Adding the cost of all projects for each Employee and saving it in new dataframe “TotalProjCost” with three columns ID, First Name, and Total cost


total_cost_df = final_df.groupby("ID")["Cost"].sum().reset_index()

In [45]:
name_df = final_df[["ID", "First Name"]].drop_duplicates()

In [46]:
TotalProjCost = pd.merge(name_df, total_cost_df, on="ID", how="inner")

In [47]:
TotalProjCost.rename(columns={"Cost": "Total Cost"}, inplace=True)

In [48]:
TotalProjCost

     ID  First Name    Total Cost
0  A001    Mr. John  5.063714e+06
1  A002  Mrs. Alice  2.680000e+06
2  A003     Mr. Tom  5.150000e+06
3  A004   Mrs. Nina  9.500000e+06
4  A005    Mrs. Amy  3.850500e+06

In [49]:
TotalProjCost.to_csv("TotalProjCost.csv", index=False)

In [50]:
#Task 10 - Printing all the employee details whose city name contains the letter “o” in it.

city_o_df = final_df[final_df["City"].str.contains("o", case=False)]

In [51]:
city_o_df

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2000000.0,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project 6,680000.0,Failed,0.0
8,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 4,5500000.0,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 12,1000000.0,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 13,3000000.0,Finished,150000.0

In [52]:
city_o_df.to_csv("CityContainsO.csv", index=False)